version: "3.3"

networks:
  nuxt:

services:

  nginx:
    build: ./dockers/nginx/
    volumes:
      - "./dockers/nginx:/etc/nginx/conf.d"
    links:
      - nuxtjs
    container_name: nuxt-nginx
    restart: always
    networks:
      - nuxt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(${NUXT_DOMAIN})" 
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver" 
      - "traefik.port=80"

  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(${API_DOMAIN})" 
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
      - "traefik.port=8383:80"
    networks:
      - nuxt

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"
    networks: 
      - nuxt
    labels: 
      - "traefik.enable=false"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - nuxt
    labels:
      - "traefik.enable=false"

  nuxtjs:
    build: ./nuxt-app/
    ports:
      - 3000:3000
    container_name: nuxt-js
    command: "npm run dev"
    networks:
      - nuxt

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik" 
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=mike.beplus@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - nuxt
