version: "3.3"

networks:
  nuxt:

services:

  nginx:
    build: ./dockers/nginx/
    volumes:
      - ./dockers/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
    links:
      - nuxtjs
    container_name: nuxt-nginx
    networks:
      - nuxt

  nuxtjs:
    build: ./nuxt-app/
    ports:
      - 3000:3000
    container_name: nuxt-js
    command: "npm run dev"
    networks:
      - nuxt

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"